import React, { createContext, useContext } from 'react';

// This is a backend-free, no-login app. This context just provides a single
// implicit local user, used e.g. for PDF "generated by" attribution.

const AuthContext = createContext(null);

const VALUE = { user: { id: 'local', full_name: 'Usuario local', email: '' } };

export const AuthProvider = ({ children }) => (
  <AuthContext.Provider value={VALUE}>{children}</AuthContext.Provider>
);

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) throw new Error('useAuth must be used within an AuthProvider');
  return context;
};
